#!/bin/bash
#
# Contoh Custom Paths Usage - YT ZIXSTYLE 2025
# Menunjukkan cara menggunakan custom path yang completely flexible
#

echo "🎯 Custom Paths Usage Examples - Completely Flexible!"
echo "════════════════════════════════════════════════════"
echo ""

echo "📋 Available Environment Variables:"
echo "   CUSTOM_VMESS_PATH       - VMess WebSocket path"
echo "   CUSTOM_VMESS_XHTTP_PATH - VMess XHTTP path (default: same as VMESS)"
echo "   CUSTOM_VMESS_GRPC       - VMess gRPC service name"
echo "   CUSTOM_VLESS_PATH       - VLess WebSocket path"
echo "   CUSTOM_VLESS_XHTTP_PATH - VLess XHTTP path (default: same as VLESS)"
echo "   CUSTOM_VLESS_GRPC       - VLess gRPC service name"
echo "   CUSTOM_TROJAN_PATH      - Trojan WebSocket path"
echo "   CUSTOM_TROJAN_GRPC      - Trojan gRPC service name"
echo "   CUSTOM_TROJANGO_PATH    - Trojan-Go WebSocket path"
echo ""

echo "🎯 Example 1: Social Media Themed Paths"
echo "────────────────────────────────────────"
echo "CUSTOM_VMESS_PATH='/facebook' \\"
echo "CUSTOM_VLESS_PATH='/instagram' \\"
echo "CUSTOM_TROJAN_PATH='/youtube' \\"
echo "CUSTOM_TROJANGO_PATH='/tiktok' \\"
echo "./xray-2025.sh"
echo ""

echo "🎯 Example 2: Professional Service Paths"
echo "─────────────────────────────────────────"
echo "CUSTOM_VMESS_PATH='/api' \\"
echo "CUSTOM_VLESS_PATH='/dashboard' \\"
echo "CUSTOM_TROJAN_PATH='/admin' \\"
echo "CUSTOM_TROJANGO_PATH='/secure' \\"
echo "./xray-2025.sh"
echo ""

echo "🎯 Example 3: Completely Random Paths"
echo "──────────────────────────────────────"
echo "CUSTOM_VMESS_PATH='/abc123xyz' \\"
echo "CUSTOM_VLESS_PATH='/def456uvw' \\"
echo "CUSTOM_TROJAN_PATH='/ghi789rst' \\"
echo "CUSTOM_TROJANGO_PATH='/jkl012mno' \\"
echo "./xray-2025.sh"
echo ""

echo "🎯 Example 4: Tech Company Paths"
echo "─────────────────────────────────"
echo "CUSTOM_VMESS_PATH='/google' \\"
echo "CUSTOM_VLESS_PATH='/microsoft' \\"
echo "CUSTOM_TROJAN_PATH='/apple' \\"
echo "CUSTOM_TROJANGO_PATH='/amazon' \\"
echo "./xray-2025.sh"
echo ""

echo "🎯 Example 5: Mixed Custom Paths"
echo "─────────────────────────────────"
echo "CUSTOM_VMESS_PATH='/facebook' \\"
echo "CUSTOM_VMESS_XHTTP_PATH='/instagram' \\"
echo "CUSTOM_VMESS_GRPC='youtube-grpc' \\"
echo "CUSTOM_VLESS_PATH='/google' \\"
echo "CUSTOM_VLESS_XHTTP_PATH='/microsoft' \\"
echo "CUSTOM_VLESS_GRPC='apple-grpc' \\"
echo "CUSTOM_TROJAN_PATH='/amazon' \\"
echo "CUSTOM_TROJAN_GRPC='netflix-grpc' \\"
echo "CUSTOM_TROJANGO_PATH='/spotify' \\"
echo "./xray-2025.sh"
echo ""

echo "🔍 How to Check Current Paths:"
echo "─────────────────────────────"
echo "cat /etc/xray/.paths"
echo ""

echo "🔄 Default Behavior (no custom paths):"
echo "──────────────────────────────────────"
echo "./xray-2025.sh  # Will generate random paths automatically"
echo ""

echo "📁 Configuration Files:"
echo "──────────────────────"
echo "/etc/xray/.paths         - All custom paths"
echo "/etc/xray/.config-details - Full configuration with UUID, keys, paths"
echo ""

echo "⚡ Key Benefits:"
echo "──────────────"
echo "✅ Completely flexible - any path you want!"
echo "✅ Anti-detection - random/custom paths hard to detect"
echo "✅ Social media cloaking - mimic real services"
echo "✅ Professional paths - look like real APIs"
echo "✅ Easy customization - just set environment variables"
echo ""

echo "💡 Pro Tips:"
echo "────────────"
echo "• Use realistic paths like /api, /dashboard for stealth"
echo "• Social media paths work great: /facebook, /instagram"
echo "• Random paths provide maximum security"
echo "• gRPC uses serviceName, not URL path"
echo "• REALITY doesn't need path (direct TCP)"
echo ""

echo "🚀 Ready to customize your Xray installation!"
echo "Just set the environment variables and run ./xray-2025.sh"
